GET http://localhost:3001/api/persons
###
GET http://localhost:3001/info
###
GET http://localhost:3001/api/persons/1
###
GET http://localhost:3001/api/persons/6
###
DELETE  http://localhost:3001/api/persons/4
###
DELETE  http://localhost:3001/api/persons/1
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "bla",
  "number": "0690"
}
###
PUT http://localhost:3001/api/persons/66ce8766d7a8895684ecc1b1
Content-Type: application/json

{
  "name": "ben",
  "number": "700"
}